//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phr_prog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drugs
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Phorm { get; set; }
        public string Dosage { get; set; }
        public string Proz { get; set; }
        public string Time { get; set; }
    }
}
